In [1]:
import pandas as pd
df_train = pd.read_parquet("train.parquet")
df_val = pd.read_parquet("val.parquet")
df_train

,rel,qid,1,2,3,4,5,6,7,8,...,127,128,129,130,131,132,133,134,135,136
1417,0,211,1.0,0.0,1.0,1.0,2.0,0.500000,0.0,0.500000,...,42.0,0.0,0.0,115.0,52534.0,34.0,76.0,0.0,0.0,0.0
1418,0,211,2.0,0.0,2.0,1.0,2.0,1.000000,0.0,1.000000,...,37.0,666.0,0.0,153.0,2074.0,3.0,7.0,0.0,0.0,0.0
1419,0,211,2.0,0.0,1.0,0.0,2.0,1.000000,0.0,0.500000,...,47.0,3.0,0.0,22420.0,1032.0,33.0,20.0,0.0,0.0,0.0
1420,0,211,1.0,0.0,1.0,0.0,1.0,0.500000,0.0,0.500000,...,20.0,0.0,10.0,3284.0,65435.0,9.0,16.0,0.0,0.0,0.0
1421,0,211,0.0,0.0,0.0,1.0,1.0,0.000000,0.0,0.000000,...,27.0,310.0,0.0,19558.0,48507.0,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722647,0,29887,3.0,0.0,1.0,1.0,3.0,1.000000,0.0,0.333333,...,34.0,10.0,41.0,3346.0,65535.0,4.0,7.0,0.0,0.0,0.0
722648,0,29887,3.0,0.0,0.0,1.0,3.0,1.000000,0.0,0.000000,...,34.0,0.0,0.0,23538.0,65535.0,2.0,6.0,0.0,0.0,0.0
722649,0,29887,3.0,0.0,2.0,2.0,3.0,1.000000,0.0,0.666667,...,126.0,2.0,1.0,1551.0,58966.0,3.0,7.0,0.0,0.0,0.0
722650,0,29887,3.0,0.0,1.0,1.0,3.0,1.000000,0.0,0.333333,...,44.0,0.0,4.0,36617.0,65535.0,2.0,6.0,0.0,0.0,0.0
722651,0,29887,2.0,0.0,0.0,0.0,2.0,0.666667,0.0,0.000000,...,43.0,0.0,2.0,587.0,58039.0,2.0,6.0,0.0,0.0,0.0